/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Node_3: THREE.Mesh;
  };
  materials: {
    ["Scene_-_Root"]: THREE.MeshPhysicalMaterial;
  };
};

const material = new THREE.MeshPhongMaterial({
  shininess: 45
})

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/graces-draco2.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node_3.geometry}
        material={material}
      />
    </group>
  );
}

useGLTF.preload("/graces-draco2.glb");